const emoji = [
" “You don’t have to be great to start, but you have to start to be great.” by Zig Ziglar",
" “One day or day one. You decide.” by unknown",
" “Now is the operative word. Everything you put in your way is just a method of putting off the hour when you could actually be doing your dream. You don’t need endless time and perfect conditions. Do it now. Do it today. Do it for twenty minutes and watch your heart start beating.” by Barbara Sher",
" “You are what you do, not what you say you do.” by Carl Jung",
" “Small deeds done are better than great deeds planned.” by Peter Marshall",
" “Dream big, start small, but most of all, start.” by Simon Sinek",
" “The man who removes a mountain begins by carrying away small stones.” by William Faulkner",
" “The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas, but there are few who decide to do something about them now.” by Nolan Bushnell",
" “People may doubt what you say, but they will believe what you do.” by Lewis Cass",
" “I know how it looks. But just start. Nothing is insurmountable.” by Lin-Manuel Miranda",
" “It does not matter how slowly you go as long as you do not stop.” by Confucius",
" “Be not afraid of growing slowly; be afraid only of standing still.” by Chinese Proverb",
" “There is only one proof of ability: action.” by Marie Ebner-Eschenbach",
" “Follow effective action with quiet reflection. From the quiet reflection will come even more effective action.” by James Levin",
" “Only put off until tomorrow what you are willing to die having left undone.” by Pablo Picasso",
" “Never confuse motion with action.” by Benjamin Franklin",
" “If you spend too much time thinking about a thing, you’ll never get it done.” by Bruce Lee",
" “Every day do something that will inch you closer to a better tomorrow.” by Doug Firebaugh",
" “The most important key to achieving great success is to decide upon your goal and launch, get started, take action, move.” by John Wooden",
" “The future is always beginning now.” by Mark Strand",
" “If what you are doing is not moving you towards your goals, then it’s moving you away from your goals.” by Brian Tracy",
" “You can’t be that kid standing at the top of the waterslide, overthinking it. You have to go down the chute.” by Tina Fey",
" “Little by little does the trick.” by Aesop",
" “Someday is not a day of the week.” by Janet Dailey",
" “The elevator to success is out of order. You’ll have to use the stairs… one step at a time.” by Joe Girard",
" “Action is a great restorer and builder of confidence. Inaction is not only the result, but the cause, of fear.” by Norman Vincent Peale",
" “I’d rather regret the things I’ve done than regret the things I haven’t done.” by Lucille Ball",
" “The secret of getting things done is to act!.” by Dante Alighieri",
" “An idea not coupled with action will never get any bigger than the brain cell it occupied.” by Arnold Henry Glasow",
" “A journey of a thousand miles begins with a single step.” by Lao Tzu",
" “One hundred percent of the shots you don’t take don’t go in.” by Wayne Gretzky",
" “Inaction breeds doubt and fear. Action breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy.” by Dale Carnegie",
" “The way to get started is to quit talking and begin doing.” by Walt Disney",
" “Take time to deliberate, but when the time for action has arrived, stop thinking and go in.” by Napolean Bonaparte",
" “Right now a moment of time is passing by… we must become that moment.” by Paul Cezanne",
" “Nothing happens until something moves.” by Albert Einstein",
" “Don’t try to rush progress. Remember, a step forward, no matter how small, is a step in the right direction. Keep believing.” by Kara Goucher",
" “Go for it now. The future is promised to no one.” by Wayne Dyer",
" “There are only two rules for being successful. One, figure out exactly what you want to do, and two, do it.” by Mario Cuomo",
" “The greatest amount of wasted time is the time not getting started.” by Dawson Trotman",
" “A year from now you will wish you had started today.” by Unknown",
" “The smallest deed is better than the grandest intention.” by Unknown",
" “Be great in act, as you have been in thought.” by Shakespeare",
" “Take the first step in faith. You don’t have to see the whole staircase; just take the first step.” by Martin Luther King Jr.",
" “The only impossible journey is the one you never begin.” by Tony Robbins",
" “Success seems to be connected with action. Successful people keep moving. They make mistakes but don’t quit.” by Conrad Hilton",
" “Every action you take is a vote for the type of person you wish to become.” by James Clear",
" “Be content to act, and leave the talking to others.” by Baltasar Gracian",
" “It is better to take many small steps in the right direction than to make a great leap forward only to stumble backward.” by Chinese Proverb",
" “Some of us are busy doing things; some of us are busy complaining.” by Debasish Mridha",
" “Wake up early and tackle the day before it tackles you. Be on offense, not defense.” by Evan Carmichael",
" “For any movement to gain momentum, it must start with a small action.” by Adam Braun",
" “The most effective way to do it, is to do it.” by Amelia Earhart",
" “Act as if everything you do makes a difference. It does.” by William James",
" “Decisions decide destiny. There is no action without decision.” by Tony Robbins",
" “Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.” by Unknown",
" “The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless your realize the situation is over, you cannot move forwar.” by Steve Maraboli",
" “Today I will do what others won't, so tomorrow I can accomplish what others can't.” by Jerry Rice",
" “The secret of getting ahead is getting started. The secret of getting started is breaking your complex, overwhelming tasks into small manageable tasks, and then starting on the first one.” by Unknown",
" “Try not. Do, or do not. There is no try.” by Yoda",
" “The most difficult thing is the decision to act; the rest is merely tenacity.” by Amelia Earhart",
" “You never know what's around the corner. It could be everything. Or it could be nothing. You keep putting one foot in front of the other, and then one day you look back and you've climbed a mountain.” by Tom Hiddleston",
" “Don’t watch the clock; do what it does. Keep going.” by Sam Levenson",
" “Infuse your life with action. Don't wait for it to happen. Make it happen. Make your own future.” by Bradley Whitford",
" “Act the way that you want to feel.” by Gretchen Rubin",
" “Even a snail will eventually reach its destination.” by Gail Tsukiyama",
" “You cannot plow a field by turning it over in your mind. To begin, begin.” by Gorden B. Hickley",
" “I think a lot of people dream. And while they are busy dreaming, the really happy people, the really successful people, the really interesting, powerful, engaged people? Are busy doing.” by Shonda Rhimes",
" “If you have a great ambition, take as big a step as possible in the direction of fulfilling it. The step may only be a tiny one, but trust that it may be the largest one possible for now.” by Mildred McAfee",
" “It is easy to sit up and take notice. What is difficult is getting up and taking action.” by Al Batt",
" “The only difference between where you are and where you want to be is the steps you haven’t taken yet.” by Hayley Solich",
" “One workout at a time. One day at a time. One meal at a time.” by Chalene Johnson",
" “Life is like riding a bicycle. To keep your balance you must keep moving.” by Albert Einstein",
" “The beginning is always today.” by Mary Shelley",
" “Attitude: It is our best friend or our worst enemy.” by John C. Maxwell",
" “It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.” by William James",
" “A healthy attitude is contagious but don’t wait to catch it from others. Be a carrier.” by Tom Stoppard",
" “Everyone faces defeat. It may be a stepping-stone or a stumbling block, depending on the mental attitude with which it is faced.” by Napoleon Hill",
" “The optimist sees the donut; the pessimist sees the hole.” by Oscar Wilde",
" “Attitude is everything, so pick a good one.” by Wayne Dyer",
" “A cloudy day is no match for a sunny disposition.” by William Arthur Ward",
" “It’s actually cool to be positive and optimistic and idealistic. It’s cool to see yourself doing beautiful, great things.” by Tom DeLonge",
" “Attitude is a little thing that makes a big difference.” by Winston Churchill",
" “Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude.” by Thomas Jefferson",
" “A strong positive attitude will create more miracles than any wonder drug.” by Patricia Neal",
" “The last of the human freedoms is to choose one’s attitude in any given set of circumstances.” by Victor Frankl",
" “You cannot have a positive life and a negative mind.” by Joyce Meyer",
" “You cannot control what happens to you, but you can control your attitude toward what happens to you, and in that, you will be mastering change rather than allowing it to master you.” by Brian Tracy",
" “Whether a glass is half full or half empty depends on the attitude of the person looking at it.” by Unknown",
" “Choosing to be positive and having a grateful attitude is going to determine how you're going to live your life.” by Joel Osteen",
" “Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.” by Mary Lou Retton",
" “Your attitude determines your altitude.” by Wayne Dyer",
" “The world of achievement has always belonged to the optimist.” by J. Harold Wilkins",
" “Take the attitude of a student… never be too big to ask questions, never know too much to learn something new.” by Maya Angelou",
" “Values are related to our emotions; just as we practice physical hygiene to preserve our physical health, we need to observe emotional hygiene to preserve a healthy mind and attitudes.” by Dalai Lama",
" “Our attitude towards life determines life’s attitude towards us.” by John Mitchell",
" “Having a positive mental attitude is asking how something can be done rather than saying it can’t be done.” by Bo Bennett",
" “If we have the attitude that it’s going to be a great day, it usually is..” by Catherine Pulsifer",
" “Ability is what you’re capable of doing. Motivation determines what you do. Attitude determines how well you do it.” by Lou Holtz",
" “Optimism is the faith that leads to achievement; nothing can be done without hope and confidence.” by Helen Keller",
" “The greatest revolution of our generation is the discovery that human beings, by changing the inner attitudes of their minds, can change the outer aspects of their lives.” by William James",
" “The most important thing you’ll ever wear is your attitude.” by Jeff Moore",
" “Our lives are not determined by what happens to us but how we react to what happens, not by what life brings us but the attitude we bring to life.” by Wade Boggs",
" “Optimism is a perfectly legitimate response to failure.” by Stephen King",
" “The positive thinker sees the invisible, feels the intangible, and achieves the impossible.” by Winston Churchill",
" “Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely.” by Roy T. Bennett",
" “No pessimist ever discovered the secrets of the stars, or sailed to an uncharted island, or opened a new heaven to the human spirit.” by Helen Keller",
" “Perpetual optimism is a force multiplier.” by Colin Powell",
" “If you don’t like something, change it. If you can’t change it, change your attitude. Don’t complain.” by Maya Angelou",
" “Sooner or later, the man who wins is the man who thinks he can.” by Vince Lomardi",
" “Choose the positive. You have a choice. You are the master of your attitude. Choose the positive, the constructive.” by Bruce Lee",
" “Optimist: someone who figures that taking a step backward after taking a step forward is not a disaster; it’s more like a cha-cha.” by Robert Brault",
" “Believe and act as if it were impossible to fail.” by Charles F. Kettering",
" “Almost every successful person begins with two beliefs: the future can be better than the present, and I have the power to make it so.” by David Brooks",
" “As soon as you trust yourself, you will know how to live.” by Johann Wolfgang von Goethe",
" “It’s not who you think you are that holds you back; it’s who you think you’re not.” by Unknown",
" “Keep your eyes on the stars and your feet on the ground.” by Theodore Roosevelt",
" “Let your hopes, not your hurts, shape your future.” by Robert Schuller",
" “First thing every morning before you arise, say out loud, ‘I believe’, three times.” by Norman Vincent Peale",
" “If I could give one tip for people – it’s not an exercise or nutrition regimen. It’s to walk your talk and believe in yourself, because at the end of the day, the dumbbell and diet don’t get you in shape. It’s your accountability to your word.” by Brett Hoebel",
" “Trust because you are willing to accept the risk, not because it’s safe or certain.” by Unknown",
" “Northing is impossible; the word itself says ‘I’m possible’!.” by Audrey Hepburn",
" “Hope fills the holes of my frustration in my heart.” by Emanuel Cleaver",
" “Believe while others are doubting.” by William Arthur Ward",
" “Magic is believing in yourself. If you can make that happen, you can make anything happen.” by Johann Wolfgang von Goethe",
" “Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.” by Dale Carnegie",
" “As you learn to trust yourself something miraculous happens. You begin to trust the process you are living and the miracles life brings!.” by Iyanla Vanzant",
" “Believe in yourself. Trust the process. Change forever.” by Bob Harper",
" “Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.” by Helen Keller",
" “Never lose hope. There are always possibilities if you just look for them.” by Catherine Pulsifer",
" “Faith is taking the first step, even when you don’t see the whole staircase.” by Martin Luther King Jr",
" “Close your eyes and imagine the best version of you possible. That’s who you really are. Now, let go of any part of you that doesn’t believe it.” by Chris Assad",
" “When you do things the right way, it will take longer; just trust the process!.” by Hopal Green",
" “Once we believe in ourselves, we can risk curiosity, wonder, spontaneous delight, or any experience that reveals the human spirit.” by E.E. Cummings",
" “Hope is a waking dream.” by Aristotle",
" “You can have anything you want if you are willing to give up the belief that you can't have it.” by Dr. Robert Anthony",
" “It always seems impossible until it’s done.” by Nelson Mandela",
" “Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.” by Norman Vincent Peale",
" “Too many people overvalue what they are not and undervalue what they are.” by Malcolm S. Forbes",
" “If you believe it will work out, you will see opportunities. If you believe it won’t, you will see obstacles.” by Wayne Dyer",
" “Hope lies in dreams, in imagination, and in the courage of those who dare to make dreams into reality.” by Jonas Salk",
" “There was never a night or a problem that could defeat sunrise or hope.” by Bernard Williams",
" “Within you right now is the power to do things you never dreamed possible. This power becomes available to you just as soon as you can change your beliefs.” by Dr. Maxwell Maltz",
" “Trust in the process as you journey through life in all its emotional highs and lows knowing each moment is sacred and that your soul is safe.” by Anna-Thea",
" “Sooner or later, those who win are those who think they can.” by Paul Tournier",
" “In fact, hope is best gained after defeat and failure, because then inner strength and toughness is produced.” by Fritz Knapp",
" “Hope is being able to see that there is light despite all of the darkness.” by Desmond Tutu",
" “Trust yourself. You know more than you think you do.” by Benjamin Spock",
" “Believe you can and you’re halfway there.” by Theodore Roosevelt",
" “To accomplish great things, we must not only act, but also dream, not only plan, but also believe.” by Anatole France",
" “Trust yourself. You've survived a lot, and you'll survive whatever is coming.” by Robert Tew",
" “I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.” by Ken Venturi",
" “I would rather have a mind opened by wonder than closed by belief.” by Gerry Spence",
" “We must accept finite disappointment, but never lose infinite hope.” by Martin Luther King Jr",
" “I learned that you have to push away the demand of people’s expectations by believing in your instincts.” by Stefano Pilati",
" “Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.” by Thich Nhat Hanh",
" “When someone tells me ‘no’, it doesn’t mean I can’t do it. It simply means I can’t do it with them.” by Karen E. Quinones Miller",
" “I know people that believe in ghosts but don’t believe in themselves.” by Mitch Hedberg",
" “Create the highest, grandest vision possible for your life, because you become what you believe.” by Oprah Winfrey",
" “Every negative belief weakens the partnership between mind and body.” by Deepak Chopra",
" “Whether you think you can or can’t, you’re right.” by Henry Ford",
" “Believe in your infinite potential. Your only limitations are those you set upon yourself.” by Roy T. Bennett",
" “Self trust is the essence of heroism.” by Ralph Waldo Emerson",
" “In any given moment we have two options: to step forward into growth or step back into safety.” by Abraham Maslow",
" “People don’t resist change. They resist being changed.” by Peter Senge",
" “You will never change your life until you change something you do daily.” by Mike Murdock",
" “Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new.” by Brian Tracy",
" “It’s not that some people have willpower and some don’t. It’s that some people are ready to change and others are not.” by James Gordon",
" “Change is possible, but it must start with self-acceptance.” by Alexander Lowen",
" “The key to change… is to let go of fear.” by Rosanne Cash",
" “If you don’t like something, change it. If you can’t change it, change your attitude. Don’t complain.” by Maya Angelou",
" “When we are no longer able to change a situation, we are challenged to change ourselves.” by Viktor Frankl",
" “If we’re growing, we’re always going to be out of our comfort zone.” by John Maxwell",
" “Be bold. Be confident. Be alive. A gallery of possibilities awaits you when you make change your friend.” by Bob Bone",
" “Don't go through life, grow through life.” by Eric Butterworth",
" “Progress is impossible without change.” by Walt Disney",
" “You must take personal responsibility. You cannot change the circumstances, the seasons, or the wind, but you can change yourself.” by Jim Rohn",
" “The easier it is to do, the harder it is to change.” by Eng’s Principle",
" “The secret of change is to focus all of your energy, not on fighting the old, but on building the new.” by Socrates",
" “If we don’t change, we don’t grow. If we don’t grow, we aren’t really living.” by Gail Sheehy",
" “Be not afraid of growing slowly, be afraid only of standing still.” by Chinese Proverb",
" “If you focus on results, you will never change. If you focus on change, you will get results.” by Jack Dixon",
" “Willpower can produce short-term change, but it creates constant internal stress because you haven’t dealt with the root cause.” by Rick Warren",
" “There's only one growth strategy: work hard.” by William Hague",
" “Be patient with yourself. You are growing stronger every day. The weight of the world will become lighter... and you will begin to shine brighter. Don't give up.” by Robert Tew",
" “Sometimes the winds of change are a hurricane.” by Derek Sivers",
" “Change begins at the end of your comfort zone.” by Roy T. Bennett",
" “When you blame others, you give up your power to change.” by Dr. Robert Anthony",
" “Grant me the serenity to accept the things I cannot change, courage to change the things I can, and wisdom to know the difference.” by Modified Serenity Prayer",
" “If you always do what you’ve always done, you’ll always get what you’ve always got.” by Henry Ford",
" “Our only security is our ability to change.” by John Lilly",
" “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.” by Albert Einstein",
" “Old ways won’t open new doors.” by Unknown",
" “You cannot expect to achieve new goals or move beyond your present circumstances unless you change.” by Les Brown",
" “Expect change. Analyze the landscape. Take the opportunities. Stop being the chess piece; become the player. It’s your move.” by Tony Robbins",
" “If it doesn’t challenge you, it doesn’t change you.” by Unknown",
" “You cannot control what happens to you, but you can control your attitude toward what happens to you, and in that, you will be mastering change rather than allowing it to master you.” by Brian Tracy",
" “The curious paradox is that when I accept myself just as I am, then I can change.” by Carl Rogers",
" “Change is hard at first, messy in the middle and gorgeous at the end.” by Unknown",
" “Habits are the compound interest of self-improvement… the same way that money multiplies through interest.” by James Clear",
" “The first step toward change is awareness. The second step is acceptance.” by Nathaniel Branden",
" “There is nothing noble about being superior to some other man. The true nobility is in being superior to your previous self.” by Ernest Hemingway",
" “We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.” by Maya Angelou",
" “Insanity: doing the same thing over and over again and expecting different results.” by Albert Einstein",
" “Not everything that is faced can be changed. But nothing can be changed until it is faced.” by James Baldwin",
" “Change is never painful; only resistance to change is painful.” by Buddha",
" “I think that we have to realize that times of stress are also times that are signals for growth, and if we use adversity properly, we can grow through adversity.” by Abraham J. Twerski",
" “Quite often we change our jobs, friends and spouses instead of changing ourselves.” by Akbarali H. Jetha",
" “I don’t think anyone can grow unless he’s loved exactly as he is now, appreciated for what he is rather than what he will be.” by Mister Rogers",
" “You cannot change your destination overnight, but you can change your direction overnight.” by Jim Rohn",
" “Life changes fast. Life changes in the instant… the ordinary instant.” by Joan Didion",
" “Comfort can be dangerous. Comfort provides a floor but also a ceiling.” by Trevor Noah",
" “Change is painful, but nothing is as painful as staying stuck somewhere you don’t belong.” by Mandy Hale",
" “Life is an ongoing process of choosing between safety (out of fear and need for defense) and risk (for the sake of progress and growth). Make the growth choice a dozen times a day.” by Abraham Maslow",
" “A mind that is stretched by a new experience can never go back to its old dimensions.” by Oliver Wendell Holmes, Jr",
" “Improvement isn’t inevitable. Change is.” by Unknown",
" “A bird is safe in its nest - but that is not what its wings are made for.” by Amit Ray",
" “Sometimes the place you are used to is not the place you belong.” by William Wheeler",
" “Life will only change when you become more committed to your dreams than you are to your comfort zone.” by Billy Cox",
" “Awareness is the greatest agent for change.” by Eckhart Tolle",
" “May your choices reflect your hopes, not your fears.” by Nelson Mandela",
" “To change a habit, make a conscious decision, then act out the new behavior.” by Maxwell Maltz",
" “Every day brings new choices.” by Martha Beck",
" “There are two primary choices in life: to accept conditions as they exist, or accept the responsibility for changing them.” by Denis Waitley",
" “If you chase two rabbits, both will escape.” by Unknown",
" “One day or day one. You decide.” by Unknown",
" “You can either experience the pain of discipline or the pain of regret. The choice is yours.” by Unknown",
" “Attitude is everything, so pick a good one.” by Wayne Dyer",
" “There are only two options regarding commitment; you’re either in or you’re out. There’s no such thing as life in-between.” by Pat Riley",
" “You can choose courage, or you can choose comfort, but you cannot choose both.” by Brene Brown",
" “The man of decision cannot be stopped! The man of indecision cannot be started! Take your own choice.” by Napoleon Hill",
" “Choose to be optimistic. It feels better.” by Dalai Lama",
" “You and only you are responsible for your life choices and decisions.” by Robert T. Kiyosaki",
" “In any given moment we have two options: to step forward into growth or step back into safety.” by Abraham Maslow",
" “We make our choices, then our choices make us.” by Abraham Maslow",
" “Don’t mourn over your bad decisions. Just start overcoming them with good ones.” by Joyce Meyer",
" “Never think that someone else knows what’s best for you.” by Maria Shriver",
" “You can steer yourself in any direction you choose.” by Dr. Seuss",
" “It's choice - not chance - that determines your destiny.” by Jean Nidetch",
" “Never make a permanent decision based on a temporary storm. No matter how raging the billows are today, remind yourself, ‘This too shall pass’!.” by T.D. Jakes",
" “Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice.” by Wayne Dyer",
" “The most important decision you make is to be in a good mood.” by Voltaire",
" “A decision made from fear is always the wrong decision.” by Tony Robbins",
" “If you choose not to decide, you still have made a choice.” by Neil Pearteady",
" “Every choice you make has an end result.” by Ziglar",
" “Once a decision is made, you should stop worrying and start working. It’s not always what we know that makes it a good decision. It is what we do to implement and execute it that makes it a good decision.” by John C. Maxwell",
" “In truth, people can generally make time for what they choose to do; it is not really the time.” by John Lubbock",
" “Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely.” by Roy T. Bennett",
" “Decision is the ultimate power. Decisions shape destiny.” by Tony Robbins",
" “Ignore the noise and follow your own choice.” by Unknown",
" “The most difficult thing is the decision to act!.” by Amelia Earhart",
" “In every single thing you do, you are choosing a direction. Your life is a product of choices.” by Dr. Kathleen Hall",
" “If you do not change direction, you may end up where you are heading.” by Lao Tzu",
" “Where you are going to spend your time and your energy is one of the most important decisions you get to make in life.” by Jeff Bezos",
" “No matter what the situation, remind yourself, I have a choice.” by Deepak Chopra",
" “You cannot make progress without making decisions.” by Jim Rohn",
" “Mindfulness is a pause – the space between stimulus and response: that’s where choice lies.” by Tara Brach",
" “Every decision you make reflects your evaluation of who you are.” by Marianne Williamson",
" “And in life, it is all about choices we make, and how the direction of our lives comes down to the choices we choose.” by Catherine Pulsifer",
" “When a decision has to be made, make it. There is no totally right time for anything.” by George S. Patton Jr",
" “The direction you choose to face determines whether you’re standing at the end or the beginning of a road.” by Richelle E. Goodrich",
" “Go in the direction of where your peace is coming from.” by C. JoyBell C",
" “At every moment, we always have a choice, even if it feels as if we don’t. Sometimes that choice may simply be to think a more positive thought.” by Tina Turner",
" “Sometimes the hardest thing and the right thing are the same.” by Unknown",
" “Life is an ongoing process of choosing between safety (out of fear and need for defense) and risk (for the sake of progress and growth). Make the growth choice a dozen times a day.” by Abraham Maslow",
" “What people have the capacity to choose, they have the ability to change.” by Madeleine Albright",
" “At any given moment, you have the power to say: this is not how the story is going to end.” by Christine Mason Miller",
" “There are only two options: make progress or make excuses.” by Unknown",
" “Any path you choose will likely be full of ups and downs, so choose the ones that bring you the most joy and make you feel most alive.” by Hilary Swank",
" “Choose the positive. You have a choice. You are the master of your attitude. Choose the positive, the constructive.” by Bruce Lee",
" “Nothing worthwhile comes easily. Work, continuous work, and hard work, is the only way to accomplish results that last.” by Hamilton Holt",
" “There are no shortcuts to any place worth going.” by Beverly Sills",
" “Continuous effort – not strength or intelligence – is the key to unlocking our potential.” by Liane Cordes",
" “You've got to get up every morning with determination if you're going to go to bed with satisfaction.” by George Lorimer",
" “When you have exhausted all possibilities, remember this - you haven’t.” by Thomas Edison",
" “Most people never run far enough on their first wind to find out they’ve got a second.” by William James",
" “There are only two options regarding commitment; you’re either in or you’re out. There’s no such thing as life in-between.” by Pat Riley",
" “A champion is simply someone who did not give up when they wanted to.” by Tom Landry",
" “The big secret in life is that there is no secret. Whatever your goal, you can get there if you’re willing to work.” by Oprah Winfrey",
" “For every pass I caught in a game, I caught a thousand in practice.” by Don Hutson",
" “There's only one growth strategy: work hard.” by William Hague",
" “Success is dependent upon the glands – sweat glands.” by Ziglar",
" “When you reach the end of your rope, tie a knot in it and hang on.” by Thomas Jefferson",
" “If you want to be the best, you can't take the path of least resistance. Every morning, you wake up, and your mind tells you it's too early, and your body tells you you're a little too sore, but you've got to look deep within yourself and know what you want and what you're striving for.” by Antonio Brown",
" “You may have to fight a battle more than once to win it.” by Margaret Thatcher",
" “You have to put in many, many, many tiny efforts that nobody sees or appreciates before you achieve anything worthwhile.” by Brian Tracy",
" “I run with heart and determination, and you can't measure heart.” by LaDainian Tomlinson",
" “Energy and persistence conquer all things.” by Benjamin Franklin",
" “Give your goals all you’ve got and you’ll be amazed at the energy that comes out of you.” by William James",
" “There’s a difference between interest and commitment. When you’re interested in doing something, you do it only when circumstances permit. When you’re committed to something, you accept no excuses, only results.” by Unknown",
" “When the going gets tough, the tough get going.” by English Proverb",
" “Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.” by Thomas Edison",
" “Nothing will work unless you do.” by Maya Angelou",
" “Stay committed to your decisions, but stay flexible in your approach.” by Tony Robbins",
" “Great difficulties may be surmounted by patience and perseverance.” by Abigail Adams",
" “Go the extra mile. It’s never crowded there.” by Wayne Dyer",
" “I hated every minute of the training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion’.” by Muhammad Ali",
" “Knowing is not enough; we must apply. Willing is not enough; we must do.” by Johann Wolfgang von Goethe",
" “Work hard, be kind, and amazing things will happen.” by Conan O'Brien",
" “It never gets easier; you just get better.” by Unknown",
" “After climbing a great hill, one only finds that there are many more hills to climb.” by Nelson Mandela",
" “Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.” by Dale Carnegie",
" “We can push ourselves further. We always have more to give.” by Simone Biles",
" “I know the price of success: dedication, hard work, and an unremitting devotion to the things you want to see happen.” by Frank Lloyd Wright",
" “Genius is 1% inspiration, 99% perspiration.” by Thomas Edison",
" “Work hard in silence, let your success be your noise.” by Unknown",
" “If you’re tired of starting over, stop giving up.” by Unknown",
" “Life will only change when you become more committed to your dreams than you are to your comfort zone.” by Billy Cox",
" “I didn’t get there by wishing for it or hoping for it, but by working for it.” by Estée Lauder",
" “Do not judge me by my successes, judge me by how many times I fell down and got back up again.” by Nelson Mandela",
" “Champions keep playing until they get it right.” by Billie Jean King",
" “I will either find a way or make one.” by Hannibal",
" “Whenever you do a thing, act as if all the world were watching.” by Thomas Jefferson",
" “I may win and I may lose, but I will never be defeated.” by Emmitt Smith",
" “Don’t be discouraged. It’s often the last key in the bunch that opens the lock.” by Unknown",
" “Work hard for what you want because it won’t come to you without a fight. You have to be strong and courageous and know that you can do anything you put your mind to. If somebody puts you down or criticizes you, just keep on believing in yourself and turn it into something positive.” by Leah LaBelle",
" “Ask yourself: ‘Can I give more?’ The answer is usually: ‘Yes’.” by Paul Tergat",
" “Look up, get up, and don’t ever give up.” by Michael Irvin",
" “An inventor fails 999 times, and if he succeeds once, he’s in.” by Charles Kettering",
" “An Always bear in mind that your own resolution to succeed is more important than any other one thing.” by Abraham Lincoln",
" “You can either experience the pain of discipline or the pain of regret. The choice is yours.” by Unknown",
" “Whatever you want to do, if you want to be great at it, you have to love it and be able to make sacrifices for it.” by Maya Angelou",
" “Winners never quit, and quitters never win.” by Vince Lombardi",
" “Keep working even when no one is watching.” by Alex Morgan",
" “Some people want it to happen, some wish it would happen, others make it happen.” by Michael Jordan",
" “Will it be easy? Nope. Worth it? Absolutely.” by Unknown",
" “The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere.” by Barack Obama",
" “Don’t watch the clock; do what it does. Keep going.” by Sam Levenson",
" “Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, ‘I will try again tomorrow’.” by Mary Anne Radmacher",
" “With confidence, you have won before you have started.” by Marcus Garvey",
" “Courage is the secret sauce that allows you to act despite your fears.” by Narayan Kamath",
" “I quit being afraid when my first venture failed and the sky didn’t fall down.” by Al Neuharth",
" “Do one thing every day that scares you.” by Unknown",
" “You are braver than you believe, stronger than you seem, and smarter than you think.” by Christopher Robin",
" “You can choose courage, or you can choose comfort, but you cannot choose both.” by Brene Brown",
" “Courage isn’t having strength to go on - it is going on when you don’t have the strength.” by Napoleon Bonaparte",
" “Don’t wait until everything is just right. It will never be perfect. There will always be challenges, obstacles and less than perfect conditions. So what. Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident, and more and more successful.” by Mark Victor Hansen",
" “Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.” by Norman Vincent Peale",
" “Experience tells you what to do; confidence allows you to do it.” by Stan Smith",
" “Courage is simply the willingness to be afraid and act anyway.” by Dr. Robert Anthony",
" “Confidence doesn’t come out of nowhere. It’s a result of something… hours and days and weeks and years of constant work and dedication.” by Roger Staubach",
" “Courage is the power to let go of the familiar.” by Raymond Lindquist",
" “Real courage is when you know you're licked before you begin, but you begin anyway and see it through no matter what.” by Harper Lee",
" “Self-confidence can be learned, practiced, and mastered – just like any other skill. Once you master it, everything in your life will change for the better.” by Barrie Davenport",
" “Stand up to your obstacles and do something about them. You will find that they haven’t half the strength you think they have.” by Norman Vincent Peale",
" “The way to develop self-confidence is to do the thing you fear.” by William Jennings Bryan",
" “I was always looking outside myself for strength and confidence but it comes from within. It is there all the time.” by Anne Freud",
" “The hero is no braver than the ordinary man, but he is brave five minutes longer.” by Ralph Waldo Emerson",
" “Whatever you can do – or dream you can do – begin it. Boldness has genius, power, and magic in it.” by Johann Wolfgang von Goethe",
" “Courage is not the absence of fear, but rather the judgment that something else is more important than fear.” by Ambrose Redmoon",
" “Courage is fear that has said its prayers.” by Dorothy Bernard",
" “If you have the courage to begin, you have the courage to succeed.” by Harry Hoover",
" “Never bend your head. Always hold it high. Look the world straight in the eye.” by Helen Keller",
" “You can’t be brave if you’ve only had wonderful things happen to you.” by Mary Tyler Moore",
" “Whatever course you decide upon, there is always someone to tell you that you are wrong. There are always difficulties arising which tempt you to believe that your critics are right. To map out a course of action and follow it to an end requires courage.” by Ralph Waldo Emerson",
" “Decide whether or not the goal is worth the risks involved. If it is, stop worrying.” by Amelia Earhart",
" “Nothing in life is to be feared; it is only to be understood. Now is the time to understand more, so that we may fear less.” by Marie Curie",
" “Your passion is waiting for your courage to catch up.” by Isabelle Lafleche",
" “The scariest moment is always just before you start. After that, things can only get better.” by Stephen King",
" “Grant me the serenity to accept the things I cannot change, courage to change the things I can, and wisdom to know the difference.” by Modified Serenity Prayer",
" “Self-confidence is a super power. Once you start to believe in yourself, magic starts happening.” by Unknown",
" “Try a thing you haven’t done three times. Once to get over the fear of doing it. Twice to learn how to do it. And a third time to figure out whether you like it or not.” by Joyce Meyer",
" “I have learned over the years that when one's mind is made up, this diminishes fear.” by Rosa Parks",
" “Be brave. Take risks. Nothing can substitute experience.” by Paulo Coelho",
" “You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. You must do the thing which you think you cannot do.” by Eleanor Roosevelt",
" “I have a lot of things to prove to myself. One is that I can live my life fearlessly.” by Oprah Winfrey",
" “You have to have confidence in your ability, and then be tough enough to follow through.” by Rosalynn Carter",
" “Never be afraid to do something new. Remember, amateurs built the Ark; professionals built the Titanic.” by Unknown",
" “No amount of security is worth the suffering of a life chained to a routine that has killed your dreams.” by Unknown",
" “Never let the fear of striking out get in your way.” by Babe Ruth",
" “Only those who dare to fail greatly can ever achieve greatly.” by Robert F. Kennedy",
" “Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.” by William Shakespeare",
" “Security is mostly a superstition. It does not exist in nature, nor do the children of men as a whole experience it. Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure, or nothing.” by Helen Keller",
" “It is confidence in our bodies, minds, and spirits that allows us to keep looking for new adventures.” by Oprah Winfrey",
" “You have to have confidence in your vision or else no one else will trust in it.” by Mary Katrantzou",
" “Only those who risk going too far can find out how far one can go.” by T.S. Eliot",
" “I am lucky that whatever fear I have inside me, my desire to win is always stronger.” by Serena Williams",
" “I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear.” by Nelson Mandela",
" “If you want to conquer fear, do not sit home and think about it. Go out and get busy.” by Dale Carnegie",
" “What we need to do is say, “What’s the smallest, tiniest thing that I can master and what’s the scariest thing I can do in front of the smallest number of people that can teach me how to dance with the fear?” Once we get good at that, we just realize that it’s not fatal.” by Seth Godin",
" “Great things are achieved only when we take great risks.” by Frederick the Great",
" “How very little can be done under the spirt of fear.” by Florence Nightingale",
" “Pride is holding your head up when everyone around you has theirs bowed. Courage is what makes you do it..” by Bryce Courtenay",
" “If you're presenting yourself with confidence, you can pull off pretty much anything.” by Katy Perry",
" “One important key to success is self-confidence. An important key to self-confidence is preparation.” by Arthur Ashe",
" “If you are insecure, guess what? The rest of the world is too. Do not overestimate the competition and underestimate yourself. You are better than you think.” by T. Harv Eker",
" “No one can make you feel inferior without your consent.” by Eleanor Roosevelt",
" “Courage is the commitment to begin without any guarantee of success.” by Johann Wolfgang von Goethe",
" “Confidence is a habit that can be developed by acting as if you already had the confidence you desire to have.” by Brian Tracy",
" “Sometimes the bravest and most important thing you can do is just show up.” by Brené Brown",
" “A goal without a plan is just a wish.” by Larry Elder",
" “Habit is habit and not to be flung out of the window by any man, but coaxed downstairs a step at a time.” by Mark Twain",
" “What you get by achieving your goals is not as important as what you become by achieving your goals.” by Henry David Thoreau",
" “You can’t do it all yourself. Don’t be afraid to rely on others to help you accomplish your goals.” by Oprah Winfrey",
" “You are never too old to set another goal or to dream a new dream.” by C.S. Lewis",
" “You will never leave where you are. until you decide where you’d rather be.” by Dexter Yager",
" “The most important key to achieving great success is to decide upon your goal and launch, get started, take action, move.” by John Wooden",
" “Motivation is what gets you started. Habit is what keeps you going.” by Jim Rohn",
" “Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude.” by Thomas Jefferson",
" “The unfortunate thing about this world is that good habits are so much easier to give up than bad ones.” by Somerset Maugham",
" “The big secret in life is that there is no secret. Whatever your goal, you can get there if you’re willing to work.” by Oprah Winfrey",
" “A habit is something you can do without thinking - which is why most of us have so many of them.” by Frank A. Clark",
" “People with clear, written goals, accomplish far more in a shorter period of time than people without them could ever imagine.” by Brian Tracy",
" “Habit is second nature, or rather, ten times nature.” by William James",
" “There is no such thing as a self-made man. You will reach your goals only with the help of others.” by George Shinn",
" “A dream is just a dream. A goal is a dream with a plan and a deadline.” by Harvey Mackay",
" “A dream becomes a goal when action is taken toward its achievement.” by Bo Bennett",
" “This one step - choosing a goal and sticking to it - changes everything.” by Scott Reed",
" “Bad habits are like a comfortable bed - easy to get into, but hard to get out of.” by Unknown",
" “Feeling sorry for yourself, and your present condition is not only a waste of energy but the worst habit you could possibly have.” by Dale Carnegie",
" “We are what we repeatedly do. Excellence, then, is not an act, but a habit.” by Aristotle",
" “You must have long-range goals to keep you from being frustrated by short-range failures.” by Charles C. Noble",
" “First we form habits; then they form us. Conquer your bad habits or they will conquer you.” by Robert Gilbert",
" “Your goals, minus your doubts, equal your reality.” by Ralph Marston",
" “A goal properly set is halfway reached.” by Zig Ziglar",
" “If what you are doing is not moving you towards your goals, then it’s moving you away from your goals.” by Brian Tracy",
" “If a goal is worth having, it’s worth blocking out the time in your day-to-day life necessary to achieve it.” by Jill Koenig",
" “People with goals succeed because they know where they’re going.” by Earl Nightingale",
" “You cannot expect to achieve new goals or move beyond your present circumstances unless you change.” by Les Brown",
" “Setting goals is the first step in turning the invisible into the visible.” by Tony Robbins",
" “Give your goals all you’ve got and you’ll be amazed at the energy that comes out of you.” by William James",
" “A nail is driven out by another nail. Habit is overcome by habit.” by Erasmus",
" “And once you understand that habits can change, you have the freedom and the responsibility to remake them.” by Charles Duhigg",
" “You will never change your life until you change something you do daily.” by Mike Murdock",
" “Successful people are simply those with successful habits.” by Brian Tracy",
" “If you chase two rabbits, both will escape.” by Unknown ",
" “When I feel tired, I just think about how great I will feel once I finally reach my goal.” by Michael Phelps",
" “Don’t be afraid to be ambitious about your goals. Hard work never stops. Neither should your dreams.” by Dwayne Johnson",
" “Decide whether or not the goal is worth the risks involved. If it is, stop worrying.” by Amelia Earhart",
" “If you don’t separate yourself from your distractions, your distractions will separate you from your goals and the life you want.” by Unknown",
" “No matter who you are, no matter what you do, you absolutely, positively do have the power to change.” by Bill Phillips",
" “Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.” by Unknown",
" “Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly.” by Stephen Covey",
" “You don’t have to be great to start, but you have to start to be great.” by Zig Ziglar",
" “No matter how slow you go you’re still lapping everyone on the couch.” by Unknown",
" “Start where you are. Use what you have. Do what you can.” by Arthur Ashe",
" “Motivation is when your dreams put on work clothes.” by Unknown",
" “If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse.” by Jim Rohn",
" “If you’re tired of starting over, stop giving up.” by Unknown",
" “If you can dream it, you can do it.” by Walt Disney",
" “You are never too old to set another goal or to dream a new dream.” by C.S. Lewis",
" “Where you start is not as important as where you finish.” by Zig Ziglar",
" “Motivation is like food for the brain. You cannot get enough in one sitting. It needs continual and regular top ups.” by Peter Davies",
" “Every moment is a fresh beginning.” by T.S. Eliot",
" “Within you right now is the power to do things you never dreamed possible. This power becomes available to you just as soon as you can change your beliefs.” by Dr. Maxwell Maltz",
" “Remember to celebrate milestones as you prepare for the road ahead.” by Nelson Mandela",
" “Put all excuses aside and remember this: YOU are capable.” by Zig Ziglar",
" “Whatever you can do – or dream you can do – begin it. Boldness has genius, power, and magic in it.” by Johann Wolfgang von Goethe",
" “Do what you can, with what you have, where you are.” by Theodore Roosevelt",
" “When you wake up in the morning, you have two choices: go back to sleep, or wake up and chase those dreams.” by Unknown",
" “Motivation is what gets you started. Habit is what keeps you going.” by Jim Rohn",
" “We can do anything we want as long as we stick to it long enough.” by Helen Keller",
" “None of us can change our yesterdays, but all of us can change our tomorrows.” by Colin Powell",
" “Make each day your masterpiece.” by John Wooden",
" “Twenty years from now, you’ll be more disappointed by the things you didn’t do, than the ones you did.” by Mark Twain",
" “Do the best you can. No one can do more than that.” by John Wooden",
" “Always remember: good things take time.” by Unknown",
" “It’s never too late - never too late to start over, never too late to be happy.” by Jane Fonda",
" “The difference between try and triumph is a little 'umph.” by Marvin Phillips",
" “Do something today that your future self will thank you for.” by Sean Patrick Flanery",
" “Ability is what you’re capable of doing. Motivation determines what you do. Attitude determines how well you do it.” by Lou Holtz",
" “Even a snail will eventually reach its destination.” by Gail Tsukiyama",
" “People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.” by Zig Ziglar",
" “Today is your opportunity to build the tomorrow you want.” by Ken Poirot",
" “Remember, as long as you are breathing, it’s never too late to start a new beginning.” by Unknown",
" “Every day do something that will inch you closer to a better tomorrow.” by Doug Firebaugh",
" “Believe you can and you’re halfway there.” by Theodore Roosevelt",
" “Wake up early and tackle the day before it tackles you. Be on offense, not defense.” by Evan Carmichael",
" “Remember, you only have to succeed the last time.” by Brian Tracy",
" “Think about winning the day. Don't worry about a week from now or a month from now — just think about one day at a time. If you are worried about the mountain in the distance, you might trip over the molehill right in front of you. Win the day!.” by Drew Brees",
" “Nobody who ever gave his best regretted it.” by George Halas",
" “When I feel tired, I just think about how great I will feel once I finally reach my goal.” by Michael Phelps",
" “This is your reminder that you can handle whatever today throws at you.” by Unknown",
" “Within our dreams and aspirations we find opportunities.” by Sugar Ray Leonard",
" “Self-acceptance opens up more possibilities of succeeding because you aren’t fighting yourself along the way.” by Shannon Ables",
" “If opportunity doesn’t knock, build a door.” by Milton Berle",
" “A wise man will make more opportunities than he finds.” by Francis Bacon",
" “To succeed, jump as quickly at opportunities as you do at conclusions.” by Benjamin Franklin",
" “If you believe it will work out, you will see opportunities. If you believe it won’t, you will see obstacles.” by Wayne Dyer",
" “A dream is the bearer of a new possibility, the enlarged horizon, the great hope.” by Howard Thurman",
" “The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.” by Winston Churchill",
" “Don’t wait for the right opportunity; create it.” by George Bernard Shaw",
" “Every new day begins with possibilities.” by Ronald Reagan",
" “Success is where preparation and opportunity meet.” by Bobby Unser",
" “Opportunity is missed by most people because it is dressed in overalls and looks like work.” by Thomas Edison",
" “Don’t be pushed by your problems; be led by your dreams.” by Ralph Waldo Emerson",
" “The Wright brothers flew right through the smoke screen of impossibility.” by Charles F. Kettering",
" “The path from dreams to success does exist.” by Kalpana Chawla",
" “Your big opportunity may be right where you are now.” by Napoleon Hill",
" “We all have possibilities we don't know about. We can do things we don't even dream we can do.” by Dale Carnegie",
" “Every experience is an opportunity to learn and grow.” by Unknown",
" “I am neither an optimist nor pessimist, but a possibilist.” by Max Lerner",
" “Failure is simply the opportunity to begin again, this time more intelligently.” by Henry Ford",
" “Opportunity is everywhere. The key is to develop the vision to see it.” by Unknown",
" “Victory comes from finding opportunities in problems.” by Sun Tzu",
" “The optimist turns the impossible into the possible; the pessimist turns the possible into the impossible.” by William Arthur Ward",
" “In the middle of every difficulty lies opportunity.” by Albert Einstein",
" “Everything negative – pressure, challenges – is all an opportunity for me to rise.” by Kobe Bryant",
" “Do you know what my favorite part of the game is? The opportunity to play.” by Mike Singletary",
" “Create the highest, grandest vision possible for your life, because you become what you believe.” by Oprah Winfrey",
" “If your dream isn’t bigger than you, there’s a problem with your dream.” by Deion Sanders",
" “I'd rather regret the risks that didn't work out than the chances I didn't take at all.” by Simone Biles",
" “If you think a thing is impossible, you’ll only make it impossible.” by Bruce Lee",
" “Each day is a new opportunity. I chose to make this day a great one.” by Louise Hay",
" “Until you’re ready to look foolish, you’ll never have the possibility of being great.” by Cher",
" “The key to realizing a dream is to focus not on success but on significance. Then even the small steps and little victories along your path will take on greater meaning.” by Oprah Winfrey",
" “Never lose hope; there are always possibilities if you just look for them.” by Catherine Pulsifer",
" “Everything you can imagine is real.” by Pablo Picasso",
" “You have to have confidence in your vision or else no one else will trust in it.” by Mary Katrantzou",
" “Impossible is just an opinion.” by Paulo Coelho",
" “I love that we get a new day… A new opportunity to move our lives in a positive direction… Let's be unencumbered by yesterday's nonsense… a fresh start… Take a deep breath, smile, and start again.” by Steve Maraboli",
" “Never let your memories be bigger than your dreams.” by Laird Hamilton",
" “Don’t let your alarm clock be the only reason you wake up.” by Ray Lewis",
" “Some people dream of success, while other people get up every morning and make it happen.” by Wayne Huizenga",
" “Have a dream, make a plan, go for it. You’ll get there, I promise.” by Zoe Koplowitz",
" “If you want to be the best, you can't take the path of least resistance. Every morning, you wake up, and your mind tells you it's too early, and your body tells you you're a little too sore, but you've got to look deep within yourself and know what you want and what you're striving for.” by Antonio Brown",
" “The benefits and possibilities that are created by being personally accountable are countless.” by Jay Fiset",
" “Northing is impossible; the word itself says ‘I’m possible’!.” by Audrey Hepburn",
" “If a window of opportunity appears, don’t pull down the shade.” by Tom Peters",
" “Give me six hours to chop down a tree and I will spend the first four sharpening the axe.” by Abraham Lincoln",
" “The backbone of success is hard work, determination, good planning, and perseverance.” by Mia Hamm",
" “Let our advance worrying become advance thinking and planning.” by Winston Churchill",
" “If plan A doesn’t work, the alphabet has 25 more letters… 204 if you’re in Japan.” by Claire Cook",
" “A dream is just a dream. A goal is a dream with a plan and a deadline.” by Harvey Mackay",
" “The time to repair the roof is when the sun is shining.” by John F. Kennedy",
" “The more time you spend contemplating what you should have done… you lose valuable time planning what you can and will do.” by Lil Wayne",
" “A good plan today is better than a perfect plan tomorrow.” by George S. Patton",
" “I am prepared for the worst, but hope for the best.” by Benjamin Disraeli",
" “Make time for planning. Wars are won in the general’s tent.” by Stephen Covey",
" “It takes as much energy to wish as it does to plan.” by Eleanor Roosevelt",
" “Every minute you spend in planning saves 10 minutes in execution; this gives you a 1,000 percent return on energy!.” by Brian Tracy",
" “Little by little does the trick.” by Aesop",
" “Don’t try to rush progress. Remember, a step forward, no matter how small, is a step in the right direction. Keep believing.” by Kara Goucher",
" “Slow, steady progress is better than daily excuses.” by Robin Sharma",
" “The only time you should ever look back is to see how far you've come.” by Mick Kremling",
" “I'll go anywhere as long as it's forward.” by Barack Obama",
" “It’s not about success; it’s about progress.” by Tony Robbins",
" “Progress is impossible without change.” by Walt Disney",
" “It is better to take many small steps in the right direction than to make a great leap forward only to stumble backward.” by Chinese Proverb",
" “Always be a work in progress.” by Emily Lillian",
" “Progress means getting nearer to the place you want to be... if you are on the wrong road, progress means doing an about-turn and walking back to the right road; and in that case the man who turns back soonest is the most progressive man.” by C.S. Lewis",
" “Comfort is the enemy of progress.” by P. T. Barnum",
" “Every day do something that will inch you closer to a better tomorrow.” by Doug Firebaugh",
" “You cannot make daily progress without making decisions.” by Jim Rohn",
" “Progress and growth are impossible if you always do things the way you've always done things.” by Wayne Dyer",
" “Some quit due to slow progress, never grasping the fact that slow progress is progress.” by Jeff Olson",
" “There are only two options: make progress or make excuses.” by Unknown",
" “I walk slowly, but I never walk backward.” by Abraham Lincoln",
" “Perfectionism doesn’t make you feel perfect; it makes you feel inadequate.” by Maria Shriver",
" “One may walk over the highest mountain one step at a time.” by John Wanamaker",
" “Courage means to keep making forward progress while you still feel afraid.” by Joyce Meyer",
" “Never discourage anyone who continually makes progress, no matter how slow.” by Plato",
" “Whatever you do you have to keep moving forward.” by Martin Luther King Jr",
" “Failure is success in progress.” by Albert Einstein",
" “All progress takes place outside the comfort zone.” by Michael John",
" “The man who removes a mountain begins by carrying away small stones.” by William Faulkner",
" “Too much looking backward is bad for progress.” by Henry Ward Beecher",
" “Little by little becomes a lot.” by Unknown",
" “If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.” by Barack Obama",
" “Strive for progress, not perfection.” by Unknown",
" “Don’t judge each day by the harvest you reap, but by the seeds you plant.” by Robert Louis Stevenson",
" “If there is no struggle, there is no progress.” by Frederick Douglas",
" “Continuos improvement is better than delayed perfection.” by Mark Twain",
" “Don’t compare your progress to that of others. We need our own time to travel our own distance.” by Mark Twain",
" “You can’t improve what you don’t measure.” by Cliff Lerner",
" “Smile, breathe, and go slowly.” by Thich Nhat Hanh",
" “If you think you’re too small to make a difference, try sleeping with a mosquito.” by Dalai Lama",
" “Success doesn't come from what you do occasionally, but what you do consistently.” by Marie Forleo",
" “Winning doesn’t always mean being first. Winning means you’re doing better than you’ve ever done before.” by Bonnie Blair",
" “Even a snail will eventually reach its destination.” by Gail Tsukiyama",
" “A stumble may prevent a fall.” by English Proverb",
" “A bend in the road is not the end of the road… unless you fail to make the turn.” by Helen Keller",
" “It’s not the mistakes in life that are important; it’s what we learn from them.” by Donna Guthrie",
" “You will face many defeats in life, but never let yourself be defeated.” by Maya Angelou",
" “Life is full of obstacle illusions.” by Grant Frazier",
" “If you find a path with no obstacles, it probably doesn’t lead anywhere.” by Unknown",
" “You don’t drown by falling in the water. You drown by staying there.” by Unknown",
" “Obstacles don’t have to stop you. If you run into a wall, don’t turn around and give up. Figure out how to climb it, go through it, or work around it.” by Michael Jordan",
" “The way I see it, if you want the rainbow, you gotta put up with the rain.” by Dolly Parton",
" “The significant problems we face cannot be solved by the same level of thinking that created them.” by Albert Einstein",
" “Sometimes the winds of change are a hurricane.” by Derek Sivers",
" “Smooth seas do not make skillful sailors.” by African Proverb",
" “If at first you don’t succeed, you are running about average.” by M.H. Alderson",
" “Stand up to your obstacles and do something about them. You will find that they haven’t half the strength you think they have.” by Norman Vincent Peale",
" “Don’t be discouraged. It’s often the last key in the bunch that opens the lock.” by Unknown",
" “When defeat comes, accept it as a signal that your plans are not sound. Rebuild those plans, and set sail once more toward your coveted goal.” by Napoleon Hill",
" “You may have to fight a battle more than once to win it.” by Margaret Thatcher",
" “It’s not whether you get knocked down; it’s whether you get up.” by Vince Lombardi",
" “Obstacles are those frightening things you see when you take your eyes off the goal.” by Henry Ford",
" “Don’t wait until everything is just right. It will never be perfect. There will always be challenges, obstacles and less than perfect conditions. So what. Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident and more and more successful.” by Mark Victor Hansen",
" “Stumbling is not falling.” by Portuguese Proverb",
" “Negative results are just what I want. They’re just as valuable to me as positive results. I can never find the thing that does the job best until I find the ones that don’t.” by Thomas Edison",
" “Fall seven times, stand up eight.” by Japanese Proverb",
" “Life’s problems wouldn’t be called hurdles if there wasn’t a way to get over them.” by Unknown",
" “Even if you fall on your face, you’re still moving forward.” by Robert C. Gallagher",
" “Sometimes when you’re in a dark place you think you’ve been buried, but you’ve actually been planted.” by Christine Caine",
" “The next best thing to winning is losing! At least you’ve been in the race.” by Nellie Hershey Tullis",
" “The road to success is dotted with many tempting parking places.” by Unknown",
" “Our greatest glory consists not in never falling, but in rising every time we fall.” by Oliver Goldsmith",
" “I have not failed. I’ve just found 10,000 ways that won’t work.” by Thomas Edison",
" “Everyone faces defeat. It may be a stepping-stone or a stumbling block, depending on the mental attitude with which it is faced.” by Napoleon Hill",
" “Just when the caterpillar thought the world was ending, he turned into a butterfly.” by Proverb",
" “Every strike brings me closer to the next home run.” by Babe Ruth",
" “I have learned that success is to be measured not so much by the position that one has reached in life as by the obstacles overcome while trying to succeed.” by Booker T. Washington",
" “I am not afraid of storms for I am learning how to sail my ship.” by Louise May Alcott",
" “The difficulties of life are intended to make us better, not bitter.” by Unknown",
" “This too will pass.” by Persian Proverb",
" “Nobody’s going to win all the time. On the highway of life you can’t always be in the fast lane.” by Haruki Murakami",
" “Most people spend more time and energy going around problems than in trying to solve them.” by Henry Ford",
" “It never gets easier; you just get better.” by Unknown",
" “You have to have the bad days to appreciate the good ones.” by Unknown",
" “I never lose. Either I win or learn.” by Nelson Mandela",
" “If you believe it will work out, you will see opportunities. If you believe it won’t, you will see obstacles.” by Wayne Dyer",
" “The person that tried his best and failed is superior to the person who never tried.” by Bud Wilkinson",
" “Don’t dwell on what went wrong. Instead, focus on what to do next. Spend your energies on moving forward toward finding the answer.” by Denis Waitley",
" “Great difficulties may be surmounted by patience and perseverance.” by Abigail Adams",
" “One of the things I learned the hard way was that it doesn’t pay to get discouraged.” by Lucille Ball",
" “The harder the battle, the sweeter the victory.” by Les Brown",
" “As long as a man stands in his own way, everything seems to be in his way.” by Ralph Waldo Emerson",
" “The man who removes a mountain begins by carrying away small stones.” by William Faulkner",
" “Sometimes, when you fall, you fly.” by Neil Gaiman",
" “You don’t overcome challenges by making them smaller but by making yourself bigger.” by John C. Maxwell",
" “Every cloud has a silver lining.” by John Milson",
" “When the going gets tough, the tough gets going.” by English Proverb",
" “Only in the darkness can you see the stars.” by Martin Luther King Jr.",
" “In three words I can sum up everything I’ve learned about life. It goes on.” by Robert Frost",
" “To be successful you must accept all challenges that come your way. You can’t just accept the ones you like.” by Mike Gafka",
" “You must have long-range goals to keep you from being frustrated by short-range failures.” by Charles C. Noble",
" “In every difficult situation is potential value. Believe this, then begin looking for it.” by Norman Vincent Peale",
" “When life gives you lemons, make lemonade.” by Proverb",
" “Keep walking through the storm. Your rainbow is waiting on the other side.” by Heather Stillufsen",
" “Every day may not be good, but there is something good in every day.” by Alice Morse Earle",
" “Still I rise.” by Maya Angelou",
" “The only real failure in life is one not learned from.” by Anthony J. D’Angelo",
" “Through every dark night, there's a bright day after that.” by Tupac Shakur",
" “If there is no struggle, there is no progress.” by Frederick Douglass",
" “There are always new, grander challenges to confront, and a true winner will embrace each one.” by Mia Hamm",
" “You're far too smart to be the only thing standing in your way.” by Unknown",
" “If you fell down yesterday, stand up today.” by H. G. Wells",
" “You can’t calm the storm, so stop trying. What you can do is calm yourself. The storm will pass.” by Timber Hawkeye",
" “The blizzard doesn’t last forever; it just seems so.” by Ray Bradbury",
" “The best way out is through.” by Robert Frost",
" “The only thing that ever sat its way to success was a hen.” by Sarah Brown",
" “When you get right down to the root of the meaning of the word succeed, you find that it simply means to follow through.” by F. W. Nichol",
" “If you want to fly, you’ve got to give up the thing that weighs you down.” by Toni Morrison",
" “Almost every successful person begins with two beliefs: the future can be better than the present, and I have the power to make it so.” by David Brooks",
" “Treat every small victory like you just won the Superbowl.” by Lewis Howes",
" “Success is the sum of small efforts, repeated day in and day out.” by Robert J. Collier",
" “Success is rarely the result of one swell swoop, but more often the culmination of many, many small victories.” by Joseph M. Marshall III",
" “Success doesn't come from what you do occasionally, but what you do consistently.” by Marie Forleo",
" “I know the price of success: dedication, hard work, and an unremitting devotion to the things you want to see happen.” by Frank Lloyd Wright",
" “You are a true success if you can trust yourself, love yourself, and be yourself.” by Negeena Sadat",
" “I failed my way to success.” by Thomas Edison",
" “Success consists of getting up just one more time than you fall.” by Oliver Goldsmith",
" “You have to put in many, many, many tiny efforts that nobody sees or appreciates before you achieve anything worthwhile.” by Brian Tracy",
" “The road to success is dotted with many tempting parking places.” by Unknown",
" “There are no secrets to success. It is the result of preparation, hard work, and learning from failure.” by Colin Powell",
" “Success does not consist in never making mistakes but in never making the same one a second time.” by George Bernard Shaw",
" “Winners never quit, and quitters never win.” by Vince Lombardi",
" “If you have the courage to begin, you have the courage to succeed.” by Harry Hoover",
" “Success is a staircase, not a doorway.” by Dottie Walters",
" “It’s the small wins on the long journey that we need in order to keep our confidence, joy and motivation alive.” by Brendon Burchard",
" “Don’t be distracted by criticism. Remember - the only taste of success some people have is when they take a bite out of you.” by Zig Ziglar",
" “All great achievements require time.” by Maya Angelou",
" “To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.” by Ralph Waldo Emerson",
" “The only place where success comes before work is in the dictionary.” by Vidal Sassoon",
" “Success is where preparation and opportunity meet.” by Bobby Unser",
" “What you get by achieving your goals is not as important as what you become by achieving your goals.” by Henry David Thoreau",
" “Put your heart, mind, and soul into even your smallest acts. This is the secret of success.” by Swami Sivananda",
" “Tiny victories are like gems scattered on your journey, notice them.” by Emma Xu",
" “A successful man is one who can lay a firm foundation with the bricks others have thrown at him.” by David Brinkley",
" “To succeed, jump as quickly at opportunities as you do at conclusions.” by Benjamin Franklin",
" “Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.” by Thomas Edison",
" “To be successful you must accept all challenges that come your way. You can’t just accept the ones you like.” by Mike Gafka",
" “Track your small wins to motivate your big accomplishments.” by Teresa Amabile",
" “Successful people have fear, successful people have doubts, and successful people have worries. They just don't let these feelings stop them.” by T. Harv Eker",
" “Victory comes from finding opportunities in problems.” by Sun Tzu",
" “Work hard in silence, let your success be the noise.” by Unknown",
" “Strive for excellence, not perfection, because we don’t live in a perfect world.” by Joyce Meyer",
" “We think, mistakenly, that success is the result of the amount of time we put in at work, instead of the quality of time we put in.” by Ariana Huffington",
" “You’re never too old to celebrate small victories!.” by Madhura Deshpande",
" “The great victory, which appears so simple today, was the result of a series of small victories that went unnoticed.” by Paulo Coelho",
" “Remember, you only have to succeed the last time.” by Brian Tracy",
" “Success is a series of small victories.” by Unknown",
" “Success is dependent upon the glands – sweat glands.” by Zig Ziglar",
" “You have to be happy for the small victories. If you aren’t happy for the small victories then you might never be happy.” by Lucas Welby",
" “To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.” by Reba McEntire",
" “Winning doesn’t always mean being first. Winning means you’re doing better than you’ve ever done before.” by Bonnie Blair",
" “Success is walking from failure to failure with no loss of enthusiasm.” by Winston Churchill",
" “When we fail to acknowledge and celebrate small victories, we get discouraged and the flame inside us starts to dwindle.” by Marvin Phillips",
" “Victory is won not in miles but in inches. Win a little now, hold your ground, and later, win a little more.” by Unknown",
" “If you really look closely, most overnight successes took a long time.” by Louis L’Amour",
" “Without continual growth and progress, such words as improvement, achievement, and success have no meaning.” by Steve Jobs",
" “Failure is not the opposite of success; it's part of success.” by Benjamin Franklin",
" “Success is liking yourself, liking what you do, and liking how you do it.” by Maya Angelou",
" “Acknowledge all of your small victories. They will eventually add up to something great.” by Kara Goucher",
" “An inventor fails 999 times, and if he succeeds once, he’s in.” by Charles Kettering",
" “For me, winning isn’t something that happens suddenly on the field when the whistle blows and the crowds roar. Winning is something that builds physically and mentally every day that you train and every night that you dream.” by Emmitt Smith",
" “Little victories lead to bigger victories that affect the battles that eventually win the war. Winning begins small.” by Travis J. Hedrick",
" “The elevator to success is out of order. You’ll have to use the stairs… one step at a time.” by Joe Girard",
" “A champion is simply someone who did not give up when they wanted to.” by Tom Landry",
" “Always bear in mind that your own resolution to succeed is more important than any other one thing.” by Abraham Lincoln",
" “The road to success is always under construction.” by Lily Tomlin",
" “The key to realizing a dream is to focus not on success but on significance — and then even the small steps and little victories along your path will take on greater meaning.” by Oprah Winfrey",
" “Every little victory counts.” by Zig Ziglar",
" “Do not judge me by my successes; judge me by how many times I fell down and got back up again.” by Nelson Mandela",
" “There is always room at the top.” by Daniel Webster",
" “I’ve failed over and over and over again in my life and that is why I succeed.” by Michael Jordan",
" “Don’t wait until you’ve reached your goal to be proud of yourself. Be proud of yourself every step of the way.” by Stephanie Averkamp",
" “The key to success is action, and the essential in action is perseverance.” by Sun Yat-sen",
" “Success is peace of mind, which is a direct result of self-satisfaction in knowing you did your best to become the best you are capable of becoming.” by John Wooden",
" “Our greatest battles are that with our own minds.” by Ziglar",
" “If you hear a voice within you say ‘you cannot paint,’ then by all means paint and that voice will be silenced.” by Ziglar",
" “What consumes your mind controls your life.” by Ziglar",
" “You don’t have to control your thoughts. You just have to stop letting them control you.” by Ziglar",
" “You cannot have a positive life and a negative mind.” by Ziglar",
" “The voice in your head that says ‘you can’t do this’ is a liar.” by Ziglar",
" “My life has been filled with terrible misfortune, most of which never happened.” by Ziglar",
" “With the new day comes new strength and new thoughts.” by Ziglar",
" “I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.” by Ziglar",
" “It is not the mountain we conquer, but ourselves.” by Ziglar",
" “Our anxiety does not come from thinking about the future, but from wanting to control it.” by Ziglar",
" “Change your thoughts and you change your world.” by Ziglar",
" “You either control your mind or it controls you.” by Ziglar",
" “Watch your thoughts, for they become words. Watch your words, for they become actions. Watch your actions, for they become habits. Watch your habits, for they become your character. Watch your character, for it becomes your destiny.” by Ziglar",
" “You can’t be that kid standing at the top of the waterslide, overthinking it. You have to go down the chute.” by Ziglar",
" “Worry is a misuse of imagination.” by Ziglar",
" “You have power over your mind – not outside events. Realize this, and you will find strength.” by Ziglar",
" “Has worrying about tomorrow every changed it?.” by Ziglar",
" “While we may not be able to control all that happens to us, we can control what happens inside us.” by Ziglar",
" “Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.” by Ziglar",
" “Our mind should be soft and open enough to understand things as they are; it is called mindfulness.” by Ziglar",
" “Minds are like parachutes. They only function properly when open.” by Ziglar",
" “Let go of the thoughts that don’t make you strong.” by Ziglar",
" “Make sure your worst enemy doesn’t live between your own two ears.” by Ziglar",
" “Use your imagination not to scare yourself to death, but to inspire yourself to life.” by Ziglar",
" “You wouldn’t worry so much about what people really thought of you if you knew just how seldom they actually dos.” by Ziglar",
" “The mind is its own place, and in itself, can make a heaven of Hell, a hell of Heaven.” by Ziglar",
" “Give space to your thoughts, clear the noise in your head, chit-chat with your inner critic, decide and move on.” by Ziglar",
" “To do: stop being so hard on myself.” by Ziglar",
" “Your body hears everything your mind says.” by Ziglar",
" “It’s not who you think you are that holds you back; it’s who you think you’re not.” by Ziglar",
" “The longest journey of any person is the journey inward.” by Ziglar",
" “In life we can have results or reasons. If you are not getting the results you want, your reasons are the lies that you keep telling yourself.” by Ziglar",
" “I will not let anyone walk through my mind with their dirty fee.” by Ziglar",
" “Your mind will quit a thousand times before your body will.” by Ziglar",
" “If you spend too much time thinking about a thing, you’ll never get it done.” by Ziglar",
" “The significant problems we face cannot be solved by the same level of thinking that created them.” by Ziglar",
" “Accountability, is the state or condition of being accountable or responsible. That is right. We are responsible for what goes on in our heads.” by Ziglar",
" “You cannot always control what goes on outside, but you can always control what goes on inside.” by Ziglar",
" “Whatever gets you moving and out of your head is good for you.” by Ziglar",
" “The body achieves what the mind believes.” by Ziglar",
" “Just one small positive thought in the morning can change your whole day.” by Ziglar",
" “Worry does not empty tomorrow of its sorrow; it empties today of its strength.” by Ziglar",
" “Be great in act, as you have been in thought.” by Ziglar",
" “The only one who can tell you ‘you can’t win’ is you and you don’t have to listen.” by Ziglar",
" “You cannot plow a field by turning it over in your mind. To begin, begin.” by Ziglar",
" “The mind is the most important part of achieving any fitness goal. Mental change always comes before physical change.” by Ziglar",
" “The same voice that says ‘give up’ can also be trained to say ‘keep going.” by Ziglar",
" “Life isn't as serious as the mind makes it out to be.” by Ziglar",
" “At every moment, we always have a choice, even if it feels as if we don’t. Sometimes that choice may simply be to think a more positive thought.” by Ziglar",
" “To worry is like rocking in a rocking chair. It gives you something to do but gets you nowhere.” by Ziglar",
" “If you are depressed you are living in the past, if you are anxious you are living in the future, if you are at peace, you are living in the present.” by Ziglar",
" “Don’t believe everything you think. Thoughts are just that - thoughts.” by Ziglar",
" “None but ourselves can free out minds.” by Ziglar",
" “All we are is the result of all we have thought.” by Ziglar",
" “If you start to think the problem is ‘out there,’ stop yourself. That thought is the problem.” by Ziglar",
" “It is confidence in our bodies, minds, and spirits that allows us to keep looking for new adventures.” by Ziglar",
" “Your mind will answer most questions if you learn to relax and wait for the answer.” by Ziglar",
" “Fears over tomorrow and regrets over yesterday are twin thieves that rob us of the moment.” by Ziglar",
" “A healthy outside starts from the inside.” by Ziglar",
" “Decide whether or not the goal is worth the risks involved. If it is, stop worrying.” by Ziglar",
" “Values are related to our emotions, just as we practice physical hygiene to preserve our physical health, we need to observe emotional hygiene to preserve a healthy mind and attitudes.” by Ziglar",
" “Now is no time to think of what you do not have. Think of what you can do with what there is.” by Ziglar",
" “You're far too smart to be the only thing standing in your way.” by Ziglar",
" “Turn off your mind, relax, and float downstream.” by Ziglar",
" “Pay attention to what you pay attention to.” by Ziglar",
" “You wouldn't worry so much about what others think of you if you realized how seldom they do.” by Ziglar",
" “It's not what you say out of your mouth that determines your life, it's what you whisper to yourself that has the most power!.” by Ziglar",
" “I’ve lived through some terrible things in my life, some of which actually happened.” by Ziglar",
" “True wisdom requires both thinking with our head and understanding with our heart.” by Ziglar",
" “Your body can stand almost anything. It’s your mind that you have to convince.” by Ziglar",
" “Your goal is not to battle with the mind, but to witness the mind.” by Ziglar",
" “May all beings have happy minds.” by Ziglar",
" “Meditation is not a way of making your mind quiet. It is a way of entering into the quiet that is already there - buried under the 50,000 thoughts the average person thinks every day.” by Ziglar",
" “Mind is a flexible mirror, adjust it, to see a better world.” by Ziglar"
]

const generateBtn = document.getElementById('btn');
document.getElementById("emoji-container").textContent = emoji[Math.floor(Math.random() * emoji.length)];
generateBtn.addEventListener('click', function () {
    let output = emoji[Math.floor(Math.random() * emoji.length)];
    document.getElementById("emoji-container").textContent = output;
})



const generateBtn2 = document.getElementById('btn2');

 generateBtn2.addEventListener('click', function () {
  var arr = [];
for (let i = 0; i<2; i++) {  
    let randomIndex = Math.floor((Math.random() * emoji.length));
    let randomElement = emoji[randomIndex] + "</br>" + "</br>";
    arr.push(randomElement);
} 
document.getElementById("emoji-container").innerHTML = arr;
})

const generateBtn3 = document.getElementById('btn3');

 generateBtn3.addEventListener('click', function () {
  var arr = [];
for (let i = 0; i<3; i++) {  
    let randomIndex = Math.floor((Math.random() * emoji.length));
    let randomElement = emoji[randomIndex] + "</br>" + "</br>";
    arr.push(randomElement);
} 
document.getElementById("emoji-container").innerHTML = arr;
})

const generateBtn4 = document.getElementById('btn4');

 generateBtn4.addEventListener('click', function () {
  var arr = [];
for (let i = 0; i<4; i++) {  
    let randomIndex = Math.floor((Math.random() * emoji.length));
    let randomElement = emoji[randomIndex] + "</br>" + "</br>";
    arr.push(randomElement);
} 
document.getElementById("emoji-container").innerHTML = arr;
})

const generateBtn5 = document.getElementById('btn5');

 generateBtn5.addEventListener('click', function () {
  var arr = [];
for (let i = 0; i<5; i++) {  
    let randomIndex = Math.floor((Math.random() * emoji.length));
    let randomElement = emoji[randomIndex] + "</br>" + "</br>";
    arr.push(randomElement);
} 
document.getElementById("emoji-container").innerHTML = arr;
})

function onMenuClick() {
    var navbar = document.getElementById("navigation-bar");
    var responsive_class_name = "responsive";

    navbar.classList.toggle(responsive_class_name);
}
